name: Laravel Auto Deploy

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.gigple }}" > ~/id_rsa_2
        chmod 600 ~ /id_rsa_2
        ssh-keyscan -H 143.198.84.212 >> ~/.ssh/known_hosts
      env:
        DEPLOY_KEY: ${{ secrets.gigple }}

    - name: Deploy Laravel Application
      run: |
        ssh 143.198.84.212 'cd /www/wwwroot/rev.gigple.com && git pull origin main'
        # ssh your-server-user@your-server-hostname-or-ip 'cd /path/to/your/laravel/app && composer install --no-interaction --prefer-dist --optimize-autoloader'
        # ssh your-server-user@your-server-hostname-or-ip 'cd /path/to/your/laravel/app && php artisan migrate --force'
      env:
        DEPLOY_KEY: ${{ secrets.gigple }}
